const CLOUD_STORAGE_BASE = 'https://env-00jy6kg7ld1o.normal.cloudstatic.cn'

const brands = {
  racket: [
    {
      name: 'Yonex',
      logo: '/static/brands/yonex.svg',
      models: [
        'Astrox 100ZZ', 'Astrox 99 Pro', 'Astrox 99 Tour', 'Astrox 99 Game', 'Astrox 99 Play',
        'Astrox 88D Pro', 'Astrox 88D Tour', 'Astrox 88D Game', 'Astrox 88D Play',
        'Astrox 88S Pro', 'Astrox 88S Tour', 'Astrox 88S Game', 'Astrox 88S Play',
        'Astrox 77 Pro', 'Astrox 77 Tour', 'Astrox 77 Game', 'Astrox 77 Play',
        'Astrox 70', 'Astrox Nextage',
        'Nanoflare 1000Z', 'Nanoflare 1000 Tour', 'Nanoflare 1000 Game', 'Nanoflare 1000 Play',
        'Nanoflare 800 Pro', 'Nanoflare 800 Tour', 'Nanoflare 800 Game', 'Nanoflare 800 Play',
        'Nanoflare 700 Pro', 'Nanoflare 700 Tour', 'Nanoflare 700 Game', 'Nanoflare 700 Play',
        'Nanoflare 555', 'Nanoflare 380', 'Nanoflare 370 Speed',
        'Arcsaber 11 Pro', 'Arcsaber 11 Tour', 'Arcsaber 11 Play',
        'Arcsaber 7 Pro', 'Arcsaber 7 Tour', 'Arcsaber 7 Play',
        'Nanoray 900', 'Nanoray 800', 'Nanoray 700',
        'Voltric Z-Force II', 'Voltric LD-Force', 'Voltric 80 E-Tune',
        'Duora 10', 'Duora Z-Strike', 'Duora 77',
      
        'ASTROX 11',
        'ASTROX POWER',
        'Astrox 007',
        'Astrox 007YONEX',
        'Astrox 100TOUR',
        'Astrox 10AX10',
        'Astrox 10YONEX',
        'Astrox 77pro4U',
        'Astrox ASTROX',
        'Astrox ASTROX100ZZ',
        'Astrox AX10',
        'Astrox AX100',
        'Astrox AX100TOUR',
        'Astrox AX100ZZ',
        'Astrox AX11pYONEX',
        'Astrox AX88DPRO',
        'Astrox AX88PLAY',
        'Astrox AX88SPRO',
        'Astrox AX99PLAY',
        'Astrox AXNT',
        'NANOFLARE 700',
        'Nanoflare 1000PLAY',
        'Nanoflare 1000tour',
        'Nanoflare 700PRO',
        'Nanoflare 700TOUR',
        'Nanoflare 8S',
        'Nanoflare AXNT',
        'Nanoflare NEX',
        'Nanoflare NF-1000ZZTOUR',
        'Nanoflare NF-NTEX',
        'Nanoflare NF700',
        'Nanoflare NF8S',
        'Nanoflare NFNTEXAGE',
        'Nanoflare nextage',
        'Nanoflare nfnt',
        'Voltric VTPW',
]
    },
    {
      name: 'Li-Ning',
      logo: '/static/brands/lining.svg',
      models: [
        'Axforce 90 Max Tiger', 'Axforce 90 Max Dragon',
        'Axforce 100 II', 'Axforce 80', 'Axforce 80 Light',
        'Axforce 70', 'Axforce 50', 'Axforce 40', 'Axforce 30', 'Axforce 20',
        'Axforce Cannon', 'Axforce Cannon Pro',
        'Bladex 900 Max Sun', 'Bladex 900 Max Moon',
        'Bladex 800', 'Bladex 700', 'Bladex 500',
        'Bladex 200', 'Bladex 100',
        'Halbertec 9000', 'Halbertec 8000', 'Halbertec 7000', 'Halbertec 5000', 'Halbertec 3000', 'Halbertec 2000',
        'Aeronaut 9000', 'Aeronaut 8000', 'Aeronaut 7000',
        'Windstorm 72', 'Windstorm 79', 'Windstorm 74',
        'Tectonic 7', 'Tectonic 9', 'Calibar 300',
        'UC 5000', 'UC 6000',
      
        'Aeronaut 9000i',
        'Axforce 08',
        'Axforce 60',
        'Axforce 80Light',
        'Axforce 90new',
        'Axforce AXFORCE',
        'Axforce CANNON',
        'Bladex 500pro',
        'Halbertec 1000',
        'Halbertec 6000',
        'Halbertec 9000POWER',
        'Halbertec Power',
]
    },
    {
      name: 'Victor',
      logo: '/static/brands/victor.png',
      models: [
        'Auraspeed 90K Metallic', 'Auraspeed 90K II', 'Auraspeed 100X Ultra',
        'Auraspeed HS Plus', 'Auraspeed Fantôme', 'Auraspeed PGS',
        'Auraspeed 90F', 'Auraspeed 100X', 'Auraspeed 99', 'Auraspeed 90S',
        'Thruster F C Ultra X', 'Thruster F Ultra', 'Thruster Ryuga II Pro',
        'Thruster Ryuga Metallic', 'Thruster Raptor', 'Thruster Merak',
        'Thruster K Falcon', 'Thruster K 12', 'Thruster K 1H',
        'DriveX 12', 'DriveX 10 Metallic', 'DriveX 8S', 'DriveX 9X', 'DriveX 1',
        'Jetspeed S 12 II', 'Jetspeed S 12 F', 'Jetspeed S 10',
        'Brave Sword 12', 'Brave Sword 12 Pro', 'Brave Sword LHI',
      
        'Auraspeed ARS-50',
        'Brave Sword 12L',
        'Jetspeed 10',
        'TK- 30',
        'TK- CLS',
        'TK- HAWK',
        'TK- MUSE',
        'TK- Onigiri',
        'TK- RAPTOR',
        'TK- RYUGA',
        'TK-RYUGA CLS',
        'TK-RYUGA MUSE',
        'Thruster 12L',
        'Thruster K Falcon HAWK',
        'Thruster K Falcon PRO',
        'Thruster Ryuga 5U',
        'Thruster Ryuga BXR',
        'Thruster Ryuga CLS',
        'Thruster Ryuga IITD',
        'Thruster Ryuga MUSE',
        'Thruster Ryuga PRO',
        'Thruster Ryuga SPORT',
        'Thruster Ryuga TK-HAWK',
        'Thruster Ryuga TK-HWQL',
        'Thruster Ryuga TK-RYUGA',
        'Thruster Ryuga pro',
]
    },
    {
      name: 'Kawasaki',
      logo: '/static/brands/kawasaki.svg',
      models: [
        'Honor S6', 'Honor S5', 'King K9', 'King K8', 'King K7',
        'Master Mao 18 II', 'Master Mao 19', 'Master 800',
        'Spider 9900 II', 'Spider 9000', 'Spider 7000',
        'Lightning 8800', 'Super Light 6820',
        'Explore 1500i', 'Corespeed 80F', 'Corespeed 70F',
      
        'Super Light 18-32',
        'Super Light 18-32LBS',
        'Super Light 35',
        'Super Light 4U',
        'Super Light 4U5U',
        'Super Light 5U',
        'Super Light 60',
        'Super Light 60s',
        'Super Light H26U',
        'Super Light LBS',
        'Super Light q5',
]
    },
    {
      name: 'Kason',
      logo: '/static/brands/kason.svg',
      models: [
        'Feather K600', 'Feather K520', 'Feather K9', 'Feather K8',
        'Force T210', 'Force T110', 'TSF 300',
        'Twister', 'B110', 'C7-PT',
        'TSF 100Ti', 'TSF 200', 'F9',
      
        'TSF 100TI',
        'TSF 105ti',
        'TSF 300Ti',
        'TSF 300a',
        'TSF 300d',
        'TSF 98',
        'TSF KASON',
        'TSF TSF',
        'TSF TSF100T105TI',
        'TSF TSF100Ti',
        'TSF TSF105TI',
        'TSF TSF105Ti',
        'TSF TSF300TI',
]
    },
    {
      name: 'Babolat',
      logo: '/static/brands/babolat.svg',
      models: [
        'X-Feel Blast', 'X-Feel Origin', 'X-Feel Origin Lite', 'X-Feel Power',
        'Satelite Blast', 'Satelite Gravity 74', 'Satelite Lite', 'Satelite Touch',
        'I-Pulse Blast', 'I-Pulse Power', '6.5 Lite S',
      
        'Babolat PS100',
]
    },
    {
      name: 'Carlton',
      logo: '/static/brands/carlton.svg',
      models: [
        'Kinesis Ultra', 'Kinesis X90', 'Kinesis Enhance 70', 'Kinesis Rapid',
        'Vapour Trail Pure', 'Vapour Trail Vanquish',
        'Powerblade Superlite', 'Fireblade 300',
        'Aeroblade 6000', 'Isoblade 6.1',
      
        'Carlton K198',
]
    },
    {
      name: 'FZ Forza',
      logo: '/static/brands/forza.png',
      models: [
        'Precision 12000 VS', 'Precision 10000 VS', 'Precision 8000 VS',
        'Precision X1', 'Precision X3', 'Precision X5',
        'Power 999', 'Power 988', 'Power 576',
        'Light 10.1', 'Light 9.1', 'Light 6.1',
        'N Force', 'CNT Power 1.0',
      ]
    },
    {
      name: 'Apacs',
      logo: '/static/brands/apacs.jpg',
      models: [
        'Fantala 6.0 Speed', 'Fantala 6.0 Control',
        'Feather Weight 75', 'Feather Weight 65', 'Feather 100',
        'Z Ziggler', 'Lethal 10', 'Lethal 9',
        'Woven Aggressive', 'Woven Control',
        'Nano Fusion Speed XR', 'Nano 9900',
        'Asgardia', 'Blend 6000', 'Dual Power Speed',
      ]
    },
    {
      name: 'Fleet/Felet',
      logo: '/static/brands/fleet.svg',
      models: [
        'Woven 1000 III', 'TJ Power', 'TJ Tech Racer 1',
        'Hyperion', 'Aero Mars', 'Blink Sword',
        'High Tension 68 II', 'Professional 8000',
      
        'Fleet/Felet F-135',
        'Fleet/Felet F-20',
        'Fleet/Felet F-5000',
        'Fleet/Felet F-5000II',
        'Fleet/Felet F-580',
        'Fleet/Felet F-6000II',
        'Fleet/Felet F-680',
        'Fleet/Felet F-850',
        'Fleet/Felet F-8600',
        'Fleet/Felet F-88',
        'Fleet/Felet F-9000I',
]
    },
    {
      name: 'Bonny',
      logo: '/static/brands/bonny.svg',
      models: [
        'Classic Carbon 8888AX',
        'Classic Carbon 8888AX Ultra',
        'Classic Carbon 8888AX III',
        'Classic Carbon 8888AX Pro',
        'Classic Carbon Phantom 90',
        'Classic Carbon Phantom 100',
        'Classic Carbon Black Tortoise',
        'Classic Carbon White Emperor',
        'Classic Carbon Prince',
        'Classic Carbon Vermilion Bird',
        'Classic Carbon 1982 B142',
        'Thunder Speed 800 Pro',
        'Shadow Speed 800 BP',
        'Sword Shadow',
        'Dragon Blade',
        'Majun',
        'Polaris',
        'Warrior 672',
        'Steel Wings J20',
        'Light Feather FT68PP',
        'Tiger Wings',
        'Warrior',
        'Cloud Roc',
        'Aurora',
      
        'Black Tortoise 90',
        'Classic Carbon 8888ax',
        'Classic Carbon III',
        'Classic Carbon PRO',
        'Classic Carbon ultra',
        'Cloud Roc 350',
        'Shadow Speed BP800',
        'Sword Shadow 242',
        'Thunder Speed 800LT',
        'Thunder Speed 800Pro',
        'Vermilion Bird 2026',
]
    },
    {
      name: 'RSL',
      logo: '/static/brands/rsl.svg',
      models: [
        'AT70',
        'AT70 Ultra',
        'Extreme Cheetah',
        'Tourney NO.1',
        'Tourney NO.3',
        'Tourney NO.4',
        'Tourney NO.5',
        'Tourney NO.6',
        'Tourney NO.7',
        'Tourney NO.10',
        'Tourney 66',
        'Ultimate',
        'Supreme',
        'Classic Tourney',
        'A9',
        'D5',
      
        'Pulse GT80X',
]
    },
    {
      name: 'DHS',
      logo: '/static/brands/dhs.svg',
      models: [
        'M-Racket',
        '101', '301', '302', '401', '402', '501', '601',
        'Shining',
        'Aeroplane',
      ]
    },
    {
      name: 'KUMPOO',
      logo: '/static/brands/kumpoo.svg',
      models: [
        'Devil',
        'Shura II',
        'Xiu Luo',
        'Leopard',
        'Houyi Pro',
        'K-520', 'K-510',
        'Explorer III',
        'Turbo 200', 'Turbo 300',
        'Silver Fox',
        'K-520 Pro',
        'Chengfeng 8U',
        'Jinsong',
        'Shi Ri',
        'Shi Ri II',
        'Shi Ri III',
        'Kuangshen',
        'Guolun 2300',
        'Guolun 2300 II',
      
        'Kuangshen 7000',
        'Kuangshen 8000',
        'Kuangshen KUMPOO',
        'Shi Ri 4U',
        'Shi Ri MAX',
]
    },
    {
      name: 'GOSEN',
      logo: '/static/brands/gosen.svg',
      models: [
        'Inferno Smart',
        'Inferno',
        'Inferno Raid',
        'Roots 5000R',
        'Roots 6000R',
        'Roots Aermet',
        'Roots Xuan',
        'Customedge Type X',
        'Customedge Type V',
        'Gungnir',
        'Lotus',
        'Ryzonic 35', 'Ryzonic 45', 'Ryzonic 55',
        'Roots 2000R', 'Roots 3000R',
      
        'Inferno AIR',
        'Inferno INFERNO',
        'Roots MUGEN',
        'Roots ROOTS',
        'Roots RYOGA',
]
    },
  ],
  shoes: [
    {
      name: 'Yonex',
      logo: '/static/brands/yonex.svg',
      models: [
        'Power Cushion 65 Z3', 'Power Cushion 65 Z2', 'Power Cushion 65 Z Wide',
        'Power Cushion Aerus Z2', 'Power Cushion Aerus Z',
        'Power Cushion Eclipsion Z3', 'Power Cushion Eclipsion Z2',
        'Power Cushion Comfort Z3', 'Power Cushion Comfort Z2',
        'Power Cushion 88 Dial 3', 'Power Cushion 88 Dial 2',
        'Power Cushion Cascade Accel', 'Power Cushion SHB-50',
      ]
    },
    {
      name: 'Victor',
      logo: '/static/brands/victor.png',
      models: [
        'P9200 III', 'P9200 II', 'P9200 TTY',
        'A970 Ace', 'A960', 'A950',
        'S82 III', 'S82 II', 'S99 Elite',
        'P8500 II', 'A790', 'A780',
        'VG2 Ace', 'AS-30',
      ]
    },
    {
      name: 'Li-Ning',
      logo: '/static/brands/lining.svg',
      models: [
        'Saga Pro', 'Saga Lite', 'Saga II',
        'Ranger TD', 'Ranger IV', 'Blade Pro',
        'BladeX DF-01 Max', 'BladeSabre Max',
        'Mirage SE', 'Cloud Ace Pro', 'Cloud Ace',
        'All-Round King', 'Yun Ting', 'Cai Fei',
      ]
    },
    {
      name: 'Mizuno',
      logo: '/static/brands/mizuno.svg',
      models: [
        'Wave Fang Pro', 'Wave Fang Zero 2', 'Wave Fang NX',
        'Wave Claw Neo 3', 'Wave Claw Neo 2', 'Wave Claw 3',
        'Wave Claw 2', 'Wave Claw EL 2',
      ]
    },
    {
      name: 'ASICS',
      logo: '/static/brands/asics.svg',
      models: [
        'Gel-Blade 8', 'Gel-Blade 7',
        'Gel-Rocket 11', 'Gel-Rocket 10',
        'Court Control FF 3', 'Court Control FF 2',
        'Blast FF', 'Upcourt 5', 'Upcourt 4',
        'Gel-Tactic', 'Gel-Court Hunter',
      ]
    },
  ],
  bag: [
    {
      name: 'Yonex',
      logo: '/static/brands/yonex.svg',
      models: [
        'Pro Racquet Bag (9R)', 'Pro Racquet Bag (6R)',
        'Pro Tournament Bag', 'Pro Backpack L', 'Pro Backpack M',
        'Expert Racquet Bag (6R)',
        'Team Racquet Bag (6R)', 'Team Backpack',
        'Active Racquet Bag (6R)', 'Club Racquet Bag',
        'Pro Support Backpack',
      ]
    },
    {
      name: 'Victor',
      logo: '/static/brands/victor.png',
      models: [
        'Professional 9R Bag', 'Professional 6R Bag',
        'Professional Backpack', 'Standard 6R Bag',
        'Standard 3R Bag', 'Standard Backpack',
        'Shuttle Bag', 'Tournament Bag',
      ]
    },
    {
      name: 'Victor',
      logo: '/static/brands/victor.png',
      models: [
        'Supreme Multithermobag (12R)', 'Supreme Multithermobag (9R)',
        'Flash Multithermobag (6R)', 'Supreme Backpack',
        'Flash Backpack', 'Standard 6R Bag',
        'Standard 3R Bag', 'Standard Backpack',
      ]
    },
  ],
  shuttle: [
    {
      name: 'Yonex',
      logo: '/static/brands/yonex.svg',
      models: [
        'Aerosensa 50 (AS-50)', 'Aerosensa 40 (AS-40)',
        'Aerosensa 30 (AS-30)', 'Aerosensa 20 (AS-20)',
        'Aerosensa 10 (AS-10)',
        'Aeroclub TR', 'League 7', 'Crosswind',
        'Mavis 2000 (Nylon)', 'Mavis 370 (Nylon)', 'Mavis 200 (Nylon)',
      ]
    },
    {
      name: 'Li-Ning',
      logo: '/static/brands/lining.svg',
      models: [
        'A+900', 'A+700', 'A+620', 'A+600', 'A+300',
        'D80', 'D70', 'D60', 'D50',
        'GP Gold (Nylon)',
      ]
    },
    {
      name: 'Victor',
      logo: '/static/brands/victor.png',
      models: [
        'Master Ace', 'Champion No.1', 'Champion No.3',
        'Gold No.1', 'Gold No.5', 'Silver No.3',
        'Flight Master (Nylon)', 'NS-2000 (Nylon)',
      ]
    },
    {
      name: 'RSL',
      logo: '/static/brands/rsl.svg',
      models: [
        'Tourney NO.1',
        'Tourney NO.3',
        'Tourney NO.4',
        'Tourney NO.5',
        'Tourney NO.6',
        'Tourney NO.7',
        'Tourney NO.10',
        'Tourney 66',
        'Ultimate',
        'Supreme',
        'Classic Tourney',
        'A9',
        'D5',
      ]
    },
    {
      name: 'DHS',
      logo: '/static/brands/dhs.svg',
      models: [
        '101', '301', '302', '401', '402',
        'Aeroplane',
      ]
    },
  ]
}

// ── Brand Display Names (with Chinese) ──
const brandDisplayNames = {
  Yonex: 'Yonex(尤尼克斯)',
  'Li-Ning': 'Li-Ning(李宁)',
  Victor: 'Victor(威克多)',
  Kawasaki: 'Kawasaki(川崎)',
  Kason: 'Kason(凯胜)',
  Babolat: 'Babolat(百宝力)',
  Carlton: 'Carlton(卡尔顿)',
  'FZ Forza': 'FZ Forza',
  Apacs: 'Apacs(阿帕斯)',
  'Fleet/Felet': 'Fleet/Felet(富力特)',
  Mizuno: 'Mizuno(美津浓)',
  ASICS: 'ASICS(亚瑟士)',
  Bonny: 'Bonny(波力)',
  RSL: 'RSL(亚狮龙)',
  DHS: 'DHS(红双喜)',
  KUMPOO: 'KUMPOO(薰风)',
  GOSEN: 'GOSEN(高神)',
}

// ── Model Display Names (with Chinese) ──
const modelDisplayNames = {
  Yonex: {
    'Astrox 100ZZ': 'Astrox 100ZZ(天斧100ZZ)',
    'Astrox 99 Pro': 'Astrox 99 Pro(天斧99Pro)',
    'Astrox 88D Pro': 'Astrox 88D Pro(天斧88DPro)',
    'Astrox 88S Pro': 'Astrox 88S Pro(天斧88SPro)',
    'Astrox 77 Pro': 'Astrox 77 Pro(天斧77Pro)',
    'Astrox 70': 'Astrox 70(天斧70)',
    'Astrox Nextage': 'Astrox Nextage(天斧Nextage)',
    'Nanoflare 1000Z': 'Nanoflare 1000Z(疾光1000Z)',
    'Nanoflare 800 Pro': 'Nanoflare 800 Pro(疾光800Pro)',
    'Nanoflare 700 Pro': 'Nanoflare 700 Pro(疾光700Pro)',
    'Nanoflare 555': 'Nanoflare 555(疾光555)',
    'Nanoflare 380': 'Nanoflare 380(疾光380)',
    'Arcsaber 11 Pro': 'Arcsaber 11 Pro(弓剑11Pro)',
    'Arcsaber 7 Pro': 'Arcsaber 7 Pro(弓剑7Pro)',
    'Nanoray 900': 'Nanoray 900(锐速900)',
    'Nanoray 800': 'Nanoray 800(锐速800)',
    'Nanoray 700': 'Nanoray 700(锐速700)',
    'Voltric Z-Force II': 'Voltric Z-Force II(VT-ZF2)',
    'Voltric LD-Force': 'Voltric LD-Force(VT-LDF)',
    'Duora 10': 'Duora 10(双刃10)',
    'Duora Z-Strike': 'Duora Z-Strike(双刃ZS)',
    'Duora 77': 'Duora 77(双刃77)',
    'ASTROX 11': 'ASTROX 11(ASTROX11)',
    'ASTROX POWER': 'ASTROX POWER(ASTROXPOWER)',
    'Arcsaber 11': 'Arcsaber 11(弓剑11)',
    'Astrox 007': 'Astrox 007(天斧007)',
    'Astrox 007YONEX': 'Astrox 007YONEX(天斧007YONEX)',
    'Astrox 10': 'Astrox 10(天斧10)',
    'Astrox 100': 'Astrox 100(天斧100)',
    'Astrox 100TOUR': 'Astrox 100TOUR(天斧100TOUR)',
    'Astrox 10AX10': 'Astrox 10AX10(天斧10AX10)',
    'Astrox 10YONEX': 'Astrox 10YONEX(天斧10YONEX)',
    'Astrox 77pro4U': 'Astrox 77pro4U(天斧77pro4U)',
    'Astrox ASTROX': 'Astrox ASTROX(天斧ASTROX)',
    'Astrox ASTROX100ZZ': 'Astrox ASTROX100ZZ(天斧ASTROX100ZZ)',
    'Astrox AX10': 'Astrox AX10(天斧AX10)',
    'Astrox AX100': 'Astrox AX100(天斧AX100)',
    'Astrox AX100TOUR': 'Astrox AX100TOUR(天斧AX100TOUR)',
    'Astrox AX100ZZ': 'Astrox AX100ZZ(天斧AX100ZZ)',
    'Astrox AX11pYONEX': 'Astrox AX11pYONEX(天斧AX11pYONEX)',
    'Astrox AX88DPRO': 'Astrox AX88DPRO(天斧AX88DPRO)',
    'Astrox AX88PLAY': 'Astrox AX88PLAY(天斧AX88PLAY)',
    'Astrox AX88SPRO': 'Astrox AX88SPRO(天斧AX88SPRO)',
    'Astrox AX99PLAY': 'Astrox AX99PLAY(天斧AX99PLAY)',
    'Astrox AXNT': 'Astrox AXNT(天斧AXNT)',
    'NANOFLARE 700': 'NANOFLARE 700(NANOFLARE700)',
    'Nanoflare 1000PLAY': 'Nanoflare 1000PLAY(疾光1000PLAY)',
    'Nanoflare 1000tour': 'Nanoflare 1000tour(疾光1000tour)',
    'Nanoflare 700PRO': 'Nanoflare 700PRO(疾光700PRO)',
    'Nanoflare 700TOUR': 'Nanoflare 700TOUR(疾光700TOUR)',
    'Nanoflare 800': 'Nanoflare 800(疾光800)',
    'Nanoflare 8S': 'Nanoflare 8S(疾光8S)',
    'Nanoflare AXNT': 'Nanoflare AXNT(疾光AXNT)',
    'Nanoflare NEX': 'Nanoflare NEX(疾光NEX)',
    'Nanoflare NF-1000ZZTOUR': 'Nanoflare NF-1000ZZTOUR(疾光NF-1000ZZTOUR)',
    'Nanoflare NF-NTEX': 'Nanoflare NF-NTEX(疾光NF-NTEX)',
    'Nanoflare NF700': 'Nanoflare NF700(疾光NF700)',
    'Nanoflare NF8S': 'Nanoflare NF8S(疾光NF8S)',
    'Nanoflare NFNTEXAGE': 'Nanoflare NFNTEXAGE(疾光NFNTEXAGE)',
    'Nanoflare nextage': 'Nanoflare nextage(疾光nextage)',
    'Nanoflare nfnt': 'Nanoflare nfnt(疾光nfnt)',
    'Voltric VTPW': 'Voltric VTPW(威力VTPW)',
  },
  'Li-Ning': {
    'Axforce 90 Max Tiger': 'Axforce 90 Max Tiger(雷霆90Max虎)',
    'Axforce 90 Max Dragon': 'Axforce 90 Max Dragon(雷霆90Max龙)',
    'Axforce 100 II': 'Axforce 100 II(雷霆100二代)',
    'Axforce 80': 'Axforce 80(雷霆80)',
    'Axforce 80 Light': 'Axforce 80 Light(雷霆80轻量版)',
    'Axforce 70': 'Axforce 70(雷霆70)',
    'Axforce 50': 'Axforce 50(雷霆50)',
    'Axforce Cannon': 'Axforce Cannon(雷霆大炮)',
    'Axforce Cannon Pro': 'Axforce Cannon Pro(雷霆大炮Pro)',
    'Bladex 900 Max Sun': 'Bladex 900 Max Sun(风刃900Max日)',
    'Bladex 900 Max Moon': 'Bladex 900 Max Moon(风刃900Max月)',
    'Bladex 800': 'Bladex 800(风刃800)',
    'Bladex 700': 'Bladex 700(风刃700)',
    'Halbertec 9000': 'Halbertec 9000(战戟9000)',
    'Halbertec 8000': 'Halbertec 8000(战戟8000)',
    'Halbertec 7000': 'Halbertec 7000(战戟7000)',
    'Aeronaut 9000': 'Aeronaut 9000(风动9000)',
    'Aeronaut 8000': 'Aeronaut 8000(风动8000)',
    'Windstorm 72': 'Windstorm 72(风影72)',
    'Windstorm 79': 'Windstorm 79(风影79)',
    'Tectonic 7': 'Tectonic 7(突袭7)',
    'Tectonic 9': 'Tectonic 9(突袭9)',
    'Calibar 300': 'Calibar 300(能量300)',
    'Aeronaut 9000i': 'Aeronaut 9000i(风动9000i)',
    'Axforce 08': 'Axforce 08(雷霆08)',
    'Axforce 100': 'Axforce 100(雷霆100)',
    'Axforce 60': 'Axforce 60(雷霆60)',
    'Axforce 80Light': 'Axforce 80Light(雷霆80Light)',
    'Axforce 90new': 'Axforce 90new(雷霆90new)',
    'Axforce AXFORCE': 'Axforce AXFORCE(雷霆AXFORCE)',
    'Axforce CANNON': 'Axforce CANNON(雷霆CANNON)',
    'Bladex 500': 'Bladex 500(风刃500)',
    'Bladex 500pro': 'Bladex 500pro(风刃500pro)',
    'Halbertec 1000': 'Halbertec 1000(战戟1000)',
    'Halbertec 2000': 'Halbertec 2000(战戟2000)',
    'Halbertec 5000': 'Halbertec 5000(战戟5000)',
    'Halbertec 6000': 'Halbertec 6000(战戟6000)',
    'Halbertec 9000POWER': 'Halbertec 9000POWER(战戟9000POWER)',
    'Halbertec Power': 'Halbertec Power(战戟Power)',
  },
  Victor: {
    'Auraspeed 90K Metallic': 'Auraspeed 90K Metallic(神速90K金属版)',
    'Auraspeed 90K II': 'Auraspeed 90K II(神速90K二代)',
    'Auraspeed 100X Ultra': 'Auraspeed 100X Ultra(神速100XUltra)',
    'Auraspeed Fantôme': 'Auraspeed Fantôme(神速幻影)',
    'Auraspeed 90F': 'Auraspeed 90F(神速90F)',
    'Auraspeed 100X': 'Auraspeed 100X(神速100X)',
    'Thruster F C Ultra X': 'Thruster F C Ultra X(黑金隼Ultra X)',
    'Thruster F Ultra': 'Thruster F Ultra(黑金隼Ultra)',
    'Thruster Ryuga II Pro': 'Thruster Ryuga II Pro(龙牙二代Pro)',
    'Thruster Ryuga Metallic': 'Thruster Ryuga Metallic(龙牙金属版)',
    'Thruster Raptor': 'Thruster Raptor(猛禽)',
    'Thruster Merak': 'Thruster Merak(大熊座)',
    'Thruster K Falcon': 'Thruster K Falcon(猎鹰)',
    'DriveX 12': 'DriveX 12(驭12)',
    'DriveX 10 Metallic': 'DriveX 10 Metallic(驭10金属版)',
    'DriveX 8S': 'DriveX 8S(驭8S)',
    'DriveX 9X': 'DriveX 9X(驭9X)',
    'Jetspeed S 12 II': 'Jetspeed S 12 II(极速12二代)',
    'Jetspeed S 12 F': 'Jetspeed S 12 F(极速12F)',
    'Jetspeed S 10': 'Jetspeed S 10(极速10)',
    'Brave Sword 12': 'Brave Sword 12(亮剑12)',
    'Brave Sword 12 Pro': 'Brave Sword 12 Pro(亮剑12Pro)',
    'Brave Sword LHI': 'Brave Sword LHI(亮剑LHI)',
    'Auraspeed ARS-50': 'Auraspeed ARS-50(神速ARS-50)',
    'Brave Sword 12L': 'Brave Sword 12L(亮剑12L)',
    'Jetspeed 10': 'Jetspeed 10(极速10)',
    'TK- 30': 'TK- 30(TK-30)',
    'TK- CLS': 'TK- CLS(TK-CLS)',
    'TK- HAWK': 'TK- HAWK(TK-HAWK)',
    'TK- MUSE': 'TK- MUSE(TK-MUSE)',
    'TK- Onigiri': 'TK- Onigiri(TK-Onigiri)',
    'TK- RAPTOR': 'TK- RAPTOR(TK-RAPTOR)',
    'TK- RYUGA': 'TK- RYUGA(TK-RYUGA)',
    'TK-RYUGA CLS': 'TK-RYUGA CLS(TK-RYUGACLS)',
    'TK-RYUGA MUSE': 'TK-RYUGA MUSE(TK-RYUGAMUSE)',
    'Thruster 12L': 'Thruster 12L(黑金隼12L)',
    'Thruster K Falcon HAWK': 'Thruster K Falcon HAWK(猎鹰HAWK)',
    'Thruster K Falcon PRO': 'Thruster K Falcon PRO(猎鹰PRO)',
    'Thruster Ryuga 5U': 'Thruster Ryuga 5U(龙牙5U)',
    'Thruster Ryuga BXR': 'Thruster Ryuga BXR(龙牙BXR)',
    'Thruster Ryuga CLS': 'Thruster Ryuga CLS(龙牙CLS)',
    'Thruster Ryuga IITD': 'Thruster Ryuga IITD(龙牙IITD)',
    'Thruster Ryuga MUSE': 'Thruster Ryuga MUSE(龙牙MUSE)',
    'Thruster Ryuga PRO': 'Thruster Ryuga PRO(龙牙PRO)',
    'Thruster Ryuga SPORT': 'Thruster Ryuga SPORT(龙牙SPORT)',
    'Thruster Ryuga TK-HAWK': 'Thruster Ryuga TK-HAWK(龙牙TK-HAWK)',
    'Thruster Ryuga TK-HWQL': 'Thruster Ryuga TK-HWQL(龙牙TK-HWQL)',
    'Thruster Ryuga TK-RYUGA': 'Thruster Ryuga TK-RYUGA(龙牙TK-RYUGA)',
    'Thruster Ryuga pro': 'Thruster Ryuga pro(龙牙pro)',
  },
  Kawasaki: {
    'Honor S6': 'Honor S6(荣耀S6)',
    'Honor S5': 'Honor S5(荣耀S5)',
    'King K9': 'King K9(王者K9)',
    'King K8': 'King K8(王者K8)',
    'King K7': 'King K7(王者K7)',
    'Master Mao 18 II': 'Master Mao 18 II(大师毛18二代)',
    'Master Mao 19': 'Master Mao 19(大师毛19)',
    'Master 800': 'Master 800(大师800)',
    'Spider 9900 II': 'Spider 9900 II(蜘蛛9900二代)',
    'Spider 9000': 'Spider 9000(蜘蛛9000)',
    'Spider 7000': 'Spider 7000(蜘蛛7000)',
    'Lightning 8800': 'Lightning 8800(闪电8800)',
    'Super Light 6820': 'Super Light 6820(超轻6820)',
    'Explore 1500i': 'Explore 1500i(探索1500i)',
    'Corespeed 80F': 'Corespeed 80F(核速80F)',
    'Corespeed 70F': 'Corespeed 70F(核速70F)',
    'Super Light 18-32': 'Super Light 18-32(超轻18-32)',
    'Super Light 18-32LBS': 'Super Light 18-32LBS(超轻18-32LBS)',
    'Super Light 35': 'Super Light 35(超轻35)',
    'Super Light 4U': 'Super Light 4U(超轻4U)',
    'Super Light 4U5U': 'Super Light 4U5U(超轻4U5U)',
    'Super Light 5U': 'Super Light 5U(超轻5U)',
    'Super Light 60': 'Super Light 60(超轻60)',
    'Super Light 60s': 'Super Light 60s(超轻60s)',
    'Super Light H26U': 'Super Light H26U(超轻H26U)',
    'Super Light LBS': 'Super Light LBS(超轻LBS)',
    'Super Light q5': 'Super Light q5(超轻q5)',
  },
  Kason: {
    'Feather K600': 'Feather K600(风羽K600)',
    'Feather K520': 'Feather K520(风羽K520)',
    'Feather K9': 'Feather K9(风羽K9)',
    'Feather K8': 'Feather K8(风羽K8)',
    'Force T210': 'Force T210(火力T210)',
    'Force T110': 'Force T110(火力T110)',
    'TSF 300': 'TSF 300(汤仙虎300)',
    'Twister': 'Twister(旋风)',
    'TSF 100Ti': 'TSF 100Ti(汤仙虎100Ti)',
    'TSF 200': 'TSF 200(汤仙虎200)',
    'F9': 'F9(峰9)',
    'TSF 100TI': 'TSF 100TI(汤仙虎100TI)',
    'TSF 105ti': 'TSF 105ti(汤仙虎105ti)',
    'TSF 300Ti': 'TSF 300Ti(汤仙虎300Ti)',
    'TSF 300a': 'TSF 300a(汤仙虎300a)',
    'TSF 300d': 'TSF 300d(汤仙虎300d)',
    'TSF 98': 'TSF 98(汤仙虎98)',
    'TSF KASON': 'TSF KASON(汤仙虎KASON)',
    'TSF TSF': 'TSF TSF(汤仙虎TSF)',
    'TSF TSF100T105TI': 'TSF TSF100T105TI(汤仙虎TSF100T105TI)',
    'TSF TSF100Ti': 'TSF TSF100Ti(汤仙虎TSF100Ti)',
    'TSF TSF105TI': 'TSF TSF105TI(汤仙虎TSF105TI)',
    'TSF TSF105Ti': 'TSF TSF105Ti(汤仙虎TSF105Ti)',
    'TSF TSF300TI': 'TSF TSF300TI(汤仙虎TSF300TI)',
  },
  Bonny: {
    'Classic Carbon 8888AX': 'Classic Carbon 8888AX(斩鬼刀)',
    'Classic Carbon 8888AX Ultra': 'Classic Carbon 8888AX Ultra(斩鬼刀Ultra)',
    'Classic Carbon 8888AX III': 'Classic Carbon 8888AX III(斩鬼刀III)',
    'Classic Carbon 8888AX Pro': 'Classic Carbon 8888AX Pro(斩鬼刀Pro)',
    'Classic Carbon Phantom 90': 'Classic Carbon Phantom 90(幻影90)',
    'Classic Carbon Phantom 100': 'Classic Carbon Phantom 100(幻影100)',
    'Classic Carbon Black Tortoise': 'Classic Carbon Black Tortoise(玄武)',
    'Classic Carbon White Emperor': 'Classic Carbon White Emperor(白帝)',
    'Classic Carbon Prince': 'Classic Carbon Prince(王子)',
    'Classic Carbon Vermilion Bird': 'Classic Carbon Vermilion Bird(朱雀)',
    'Classic Carbon 1982 B142': '1982 B142(波力1982)',
    'Thunder Speed 800 Pro': 'Thunder Speed 800 Pro(雷速800Pro)',
    'Shadow Speed 800 BP': 'Shadow Speed 800 BP(影速800BP)',
    'Sword Shadow': 'Sword Shadow(剑影)',
    'Dragon Blade': 'Dragon Blade(龙鳞之刃)',
    'Majun': 'Majun(魔君)',
    'Polaris': 'Polaris(极星)',
    'Warrior 672': 'Warrior 672(战神672)',
    'Steel Wings J20': 'Steel Wings J20(钢铁之翼J20)',
    'Light Feather FT68PP': 'Light Feather FT68PP(轻羽FT68PP)',
    'Tiger Wings': 'Tiger Wings(虎翼)',
    'Warrior': 'Warrior(武者)',
    'Cloud Roc': 'Cloud Roc(云鹏)',
    'Aurora': 'Aurora(极光)',
    'Black Tortoise 90': 'Black Tortoise 90(玄武90)',
    'Classic Carbon 8888': 'Classic Carbon 8888(斩鬼刀8888)',
    'Classic Carbon 8888ax': 'Classic Carbon 8888ax(斩鬼刀8888ax)',
    'Classic Carbon III': 'Classic Carbon III(斩鬼刀III)',
    'Classic Carbon PRO': 'Classic Carbon PRO(斩鬼刀PRO)',
    'Classic Carbon ultra': 'Classic Carbon ultra(斩鬼刀ultra)',
    'Cloud Roc 350': 'Cloud Roc 350(云鹏350)',
    'Phantom 100': 'Phantom 100(幻影100)',
    'Phantom 90': 'Phantom 90(幻影90)',
    'Shadow Speed BP800': 'Shadow Speed BP800(影速BP800)',
    'Sword Shadow 242': 'Sword Shadow 242(剑影242)',
    'Thunder Speed 800': 'Thunder Speed 800(雷速800)',
    'Thunder Speed 800LT': 'Thunder Speed 800LT(雷速800LT)',
    'Thunder Speed 800Pro': 'Thunder Speed 800Pro(雷速800Pro)',
    'Vermilion Bird 2026': 'Vermilion Bird 2026(朱雀2026)',
  },
  RSL: {
    'AT70': 'AT70(亚狮龙AT70)',
    'AT70 Ultra': 'AT70 Ultra(脉冲AT70Ultra)',
    'Extreme Cheetah': 'Extreme Cheetah(极速豹)',
    'Tourney NO.1': 'Tourney NO.1(锦标赛1号)',
    'Tourney NO.3': 'Tourney NO.3(锦标赛3号)',
    'Tourney NO.4': 'Tourney NO.4(锦标赛4号)',
    'Tourney NO.5': 'Tourney NO.5(锦标赛5号)',
    'Tourney NO.6': 'Tourney NO.6(锦标赛6号)',
    'Tourney NO.7': 'Tourney NO.7(锦标赛7号)',
    'Tourney NO.10': 'Tourney NO.10(锦标赛10号)',
    'Tourney 66': 'Tourney 66(锦标赛66)',
    'Ultimate': 'Ultimate(终极)',
    'Supreme': 'Supreme(至尊)',
    'Classic Tourney': 'Classic Tourney(经典锦标赛)',
    'A9': 'A9(A9)',
    'D5': 'D5(D5)',
    'Pulse GT80X': 'Pulse GT80X(脉冲GT80X)',
  },
  DHS: {
    'M-Racket': 'M-Racket(魔拍)',
    '101': '101',
    '301': '301',
    '302': '302',
    '401': '401',
    '402': '402',
    '501': '501',
    '601': '601',
    'Shining': 'Shining(闪光)',
    'Aeroplane': 'Aeroplane(航空)',
  },
  KUMPOO: {
    'Devil': 'Devil(魔王)',
    'Shura II': 'Shura II(修罗II)',
    'Xiu Luo': 'Xiu Luo(修罗)',
    'Leopard': 'Leopard(豹)',
    'Houyi Pro': 'Houyi Pro(厚羿PRO)',
    'Explorer III': 'Explorer III(探索者三代)',
    'Turbo 200': 'Turbo 200(涡轮200)',
    'Turbo 300': 'Turbo 300(涡轮300)',
    'Silver Fox': 'Silver Fox(银狐)',
    'K-510': 'K-510',
    'K-520': 'K-520',
    'K-520 Pro': 'K-520 Pro',
    'Chengfeng 8U': 'Chengfeng 8U(乘风8U)',
    'Jinsong': 'Jinsong(劲松)',
    'Shi Ri': 'Shi Ri(蚀日)',
    'Shi Ri II': 'Shi Ri II(蚀日II)',
    'Shi Ri III': 'Shi Ri III(蚀日III)',
    'Kuangshen': 'Kuangshen(狂蟒)',
    'Guolun 2300': 'Guolun 2300(国伦2300)',
    'Guolun 2300 II': 'Guolun 2300 II(国伦2300二代)',
    'Kuangshen 7000': 'Kuangshen 7000(狂蟒7000)',
    'Kuangshen 8000': 'Kuangshen 8000(狂蟒8000)',
    'Kuangshen KUMPOO': 'Kuangshen KUMPOO(狂蟒KUMPOO)',
    'Shi Ri 4U': 'Shi Ri 4U(蚀日4U)',
    'Shi Ri MAX': 'Shi Ri MAX(蚀日MAX)',
  },
  GOSEN: {
    'Inferno Smart': 'Inferno Smart(魅剑Smart)',
    'Inferno': 'Inferno(魅剑)',
    'Inferno Raid': 'Inferno Raid(魅剑Raid)',
    'Roots 5000R': 'Roots 5000R(凌驾5000R)',
    'Roots 6000R': 'Roots 6000R(凌驾6000R)',
    'Roots Aermet': 'Roots Aermet(凌驾天龙)',
    'Roots Xuan': 'Roots Xuan(极炫)',
    'Customedge Type X': 'Customedge Type X(定角X型)',
    'Customedge Type V': 'Customedge Type V(定角V型)',
    'Gungnir': 'Gungnir(永恒之枪)',
    'Lotus': 'Lotus(莲花)',
    'Ryzonic 35': 'Ryzonic 35(雷音35)',
    'Ryzonic 45': 'Ryzonic 45(雷音45)',
    'Ryzonic 55': 'Ryzonic 55(雷音55)',
    'Roots 2000R': 'Roots 2000R(凌驾2000R)',
    'Roots 3000R': 'Roots 3000R(凌驾3000R)',
    'Inferno AIR': 'Inferno AIR(魅剑AIR)',
    'Inferno INFERNO': 'Inferno INFERNO(魅剑INFERNO)',
    'Roots MUGEN': 'Roots MUGEN(凌驾MUGEN)',
    'Roots ROOTS': 'Roots ROOTS(凌驾ROOTS)',
    'Roots RYOGA': 'Roots RYOGA(凌驾RYOGA)',
  },
  'Fleet/Felet': {
    'Woven 1000 III': 'Woven 1000 III(woven1000三代)',
    'Fleet/Felet F-135': 'Fleet/Felet F-135(F-135)',
    'Fleet/Felet F-20': 'Fleet/Felet F-20(F-20)',
    'Fleet/Felet F-5000': 'Fleet/Felet F-5000(F-5000)',
    'Fleet/Felet F-5000II': 'Fleet/Felet F-5000II(F-5000II)',
    'Fleet/Felet F-580': 'Fleet/Felet F-580(F-580)',
    'Fleet/Felet F-6000II': 'Fleet/Felet F-6000II(F-6000II)',
    'Fleet/Felet F-680': 'Fleet/Felet F-680(F-680)',
    'Fleet/Felet F-850': 'Fleet/Felet F-850(F-850)',
    'Fleet/Felet F-8600': 'Fleet/Felet F-8600(F-8600)',
    'Fleet/Felet F-88': 'Fleet/Felet F-88(F-88)',
    'Fleet/Felet F-9000I': 'Fleet/Felet F-9000I(F-9000I)',
  },
}

const modelImages = {
  Yonex: {
    'Astrox 100ZZ': '/static/models/yonex/astrox-100zz.jpg',
    'Astrox 99 Pro': '/static/models/yonex/astrox-99-pro.jpg',
    'Nanoflare 1000Z': '/static/models/yonex/nanoflare-1000z.jpg',
    'Arcsaber 11 Pro': '/static/models/yonex/arcsaber-11-pro.jpg',
    'Astrox 88D Pro': '/static/models/yonex/astrox-88d-pro.jpg',
    'Astrox 88S Pro': '/static/models/yonex/astrox-88s-pro.jpg',
    'Astrox 77 Pro': '/static/models/yonex/astrox-77-pro.jpg',
    'Nanoflare 800 Pro': '/static/models/yonex/nanoflare-800-pro.jpg',
    'Nanoflare 700 Pro': '/static/models/yonex/nanoflare-700-pro.jpg',
    'Arcsaber 7 Pro': '/static/models/yonex/arcsaber-7-pro.jpg',
    'Power Cushion 65 Z3': '/static/models/yonex/pc-65z3.jpg',
    'Power Cushion Aerus Z2': '/static/models/yonex/pc-aerus-z2.jpg',
    'Power Cushion Eclipsion Z3': '/static/models/yonex/pc-eclipsion-z3.jpg',
    'Pro Racquet Bag (9R)': '/static/models/yonex/bag-pro-9r.jpg',
    'Aerosensa 50 (AS-50)': '/static/models/yonex/as-50.jpg',
    'Aerosensa 30 (AS-30)': '/static/models/yonex/as-30.jpg',
  },
  Victor: {
    'Auraspeed 90K Metallic': '/static/models/victor/auraspeed-90k-metallic.jpg',
    'Auraspeed 100X Ultra': '/static/models/victor/auraspeed-100x-ultra.jpg',
    'Thruster F C Ultra X': '/static/models/victor/thruster-fc-ultra-x.jpg',
    'Thruster Ryuga II Pro': '/static/models/victor/thruster-ryuga-ii-pro.jpg',
    'DriveX 10 Metallic': '/static/models/victor/drivex-10-metallic.jpg',
    'Jetspeed S 12 II': '/static/models/victor/jetspeed-s12-ii.jpg',
    'P9200 III': '/static/models/victor/p9200-iii.jpg',
    'P9200 TTY': '/static/models/victor/p9200-tty.jpg',
    'A970 Ace': '/static/models/victor/a970-ace.jpg',
    'S82 III': '/static/models/victor/s82-iii.jpg',
    'Champion No.1': '/static/models/victor/champion-no1.jpg',
    'Master Ace': '/static/models/victor/master-ace.jpg',
    'Supreme Multithermobag (9R)': '/static/models/victor/bag-supreme-9r.jpg',
  },
  'Li-Ning': {
    'Axforce 90 Max Tiger': '/static/models/lining/axforce-90-tiger.jpg',
    'Axforce 90 Max Dragon': '/static/models/lining/axforce-90-dragon.jpg',
    'Bladex 900 Max Sun': '/static/models/lining/bladex-900-sun.jpg',
    'Bladex 900 Max Moon': '/static/models/lining/bladex-900-moon.jpg',
    'Halbertec 9000': '/static/models/lining/halbertec-9000.jpg',
    'Axforce 100 II': '/static/models/lining/axforce-100-ii.jpg',
    'Saga Pro': '/static/models/lining/saga-pro.jpg',
    'Ranger TD': '/static/models/lining/ranger-td.jpg',
    'A+900': '/static/models/lining/a-plus-900.jpg',
  },
  Mizuno: {
    'Wave Fang Pro': '/static/models/mizuno/wave-fang-pro.jpg',
    'Wave Fang Zero 2': '/static/models/mizuno/wave-fang-zero-2.jpg',
    'Wave Claw Neo 3': '/static/models/mizuno/wave-claw-neo-3.jpg',
  },
  ASICS: {
    'Gel-Blade 8': '/static/models/asics/gel-blade-8.jpg',
    'Gel-Rocket 11': '/static/models/asics/gel-rocket-11.jpg',
    'Court Control FF 3': '/static/models/asics/court-control-ff-3.jpg',
  },
  Babolat: {
    'X-Feel Blast': '/static/models/babolat/x-feel-blast.jpg',
    'Satelite Blast': '/static/models/babolat/satelite-blast.jpg',
    'Babolat PS100': 'Babolat PS100(PS100)',
  },
  Carlton: {
    'Kinesis Ultra': '/static/models/carlton/kinesis-ultra.jpg',
    'Vapour Trail Pure': '/static/models/carlton/vapour-trail-pure.jpg',
    'Carlton K198': 'Carlton K198(K198)',
  },
  'FZ Forza': {
    'Precision 12000 VS': '/static/models/forza/precision-12000-vs.jpg',
    'Power 999': '/static/models/forza/power-999.jpg',
  },
  Kawasaki: {
    'Honor S6': '/static/models/kawasaki/honor-s6.jpg',
    'King K9': '/static/models/kawasaki/king-k9.jpg',
  },
  Kason: {
    'Feather K600': '/static/models/kason/feather-k600.jpg',
  },
  Apacs: {
    'Fantala 6.0 Speed': '/static/models/apacs/fantala-60-speed.jpg',
    'Z Ziggler': '/static/models/apacs/z-ziggler.jpg',
  },
  'Fleet/Felet': {
    'Woven 1000 III': '/static/models/fleet/woven-1000-iii.jpg',
    'TJ Power': '/static/models/fleet/tj-power.jpg',
  },
  Bonny: {
    'Classic Carbon 8888AX': '/static/models/bonny/8888ax.jpg',
    'Classic Carbon Phantom 90': '/static/models/bonny/phantom-90.jpg',
    'Classic Carbon Black Tortoise': '/static/models/bonny/black-tortoise.jpg',
    'Steel Wings J20': '/static/models/bonny/steel-wings-j20.jpg',
    'Light Feather FT68PP': '/static/models/bonny/ft68pp.jpg',
  },
  RSL: {
    'AT70': '/static/models/rsl/at70.jpg',
    'AT70 Ultra': '/static/models/rsl/at70-ultra.jpg',
    'Extreme Cheetah': '/static/models/rsl/extreme-cheetah.jpg',
    'Tourney NO.7': '/static/models/rsl/tourney-no7.jpg',
    'Tourney NO.5': '/static/models/rsl/tourney-no5.jpg',
    'Tourney NO.4': '/static/models/rsl/tourney-no4.jpg',
  },
  DHS: {
    'M-Racket': '/static/models/dhs/m-racket.jpg',
    '301': '/static/models/dhs/301.jpg',
  },
  KUMPOO: {
    'Devil': '/static/models/kumpoo/devil.jpg',
    'Shura II': '/static/models/kumpoo/shura-ii.jpg',
    'Chengfeng 8U': '/static/models/kumpoo/chengfeng-8u.jpg',
    'Jinsong': '/static/models/kumpoo/jinsong.jpg',
    'Shi Ri II': '/static/models/kumpoo/shi-ri-ii.jpg',
    'Kuangshen': '/static/models/kumpoo/kuangshen.jpg',
    'Guolun 2300': '/static/models/kumpoo/guolun-2300.jpg',
  },
  GOSEN: {
    'Inferno Smart': '/static/models/gosen/inferno-smart.jpg',
    'Inferno': '/static/models/gosen/inferno.jpg',
    'Roots 5000R': '/static/models/gosen/roots-5000r.jpg',
    'Roots Xuan': '/static/models/gosen/roots-xuan.jpg',
    'Gungnir': '/static/models/gosen/gungnir.jpg',
    'Lotus': '/static/models/gosen/lotus.jpg',
    'Ryzonic 45': '/static/models/gosen/ryzonic-45.jpg',
  },
}

export const equipmentData = brands

export function getBrandsByType(type) {
  const typeData = brands[type]
  if (!typeData) return []
  return typeData.map(b => ({ name: b.name, logo: b.logo }))
}

export function getModelsByBrand(type, brandName) {
  const typeData = brands[type]
  if (!typeData) return []
  const brand = typeData.find(b => b.name === brandName)
  if (!brand) return []
  return brand.models
}

export function getModelImageUrl(brandName, modelName) {
  const brandImages = modelImages[brandName]
  if (brandImages && brandImages[modelName]) {
    return CLOUD_STORAGE_BASE + brandImages[modelName]
  }
  return getBrandLogo(brandName)
}

export function getBrandLogo(brandName) {
  for (const type of Object.keys(brands)) {
    const brand = brands[type].find(b => b.name === brandName)
    if (brand) return brand.logo
  }
  return null
}

export function getBrandDisplayName(brandName) {
  return brandDisplayNames[brandName] || brandName
}

export function getModelDisplayName(brandName, modelName) {
  const brandModels = modelDisplayNames[brandName]
  return (brandModels && brandModels[modelName]) || modelName
}

export const EQUIP_TYPE_ICONS = {
  racket: '\ue622',
  shoes: '\ue6a0',
  bag: '\ue60a',
  shuttle: '\ue7a3',
  socks: '\ue606',
  waist: '\ue630',
  knee: '\ue608',
  ankle: '\ue650',
  other: '其他'
}
